title:              The File Drawer
tagline:            where the sun does not shine
description:        Stuff that didn't work or too insignificant to publish

# GitHub Pages / Jekyll configuration
baseurl:            https://chooyr.github.io/p-0.06
permalink:          :title/
paginate:           5
defaults:
issues_repo:        chooyr/p-0.06
-
    scope:
      path:         https://chooyr.github.io/p-0.06/
    values:
      layout:       post
